import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

// Falls back to the canonical www origin, not localhost: metadataBase makes
// every og:image / twitter:image URL absolute, so a missing env var used to
// publish links pointing at localhost or at a per-deployment vercel.app host.
// www rather than the apex avoids a second redirect hop for crawlers.
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.courtfuel.app";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  alternates: { canonical: "/" },
  title: "CourtFuel — AI nutrition for basketball players",
  description:
    "Scan any meal, get a basketball-tuned score, fuel your game. Free on the App Store for iPhone.",
  openGraph: {
    title: "CourtFuel — AI nutrition for basketball players",
    description:
      "Scan any meal, get a basketball-tuned score, fuel your game. Free on the App Store for iPhone.",
    type: "website",
  },
  // OG image is generated by src/app/opengraph-image.tsx
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-cf-black text-white">
        <a
          href="#content"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-md focus:bg-white focus:px-4 focus:py-2 focus:font-semibold focus:text-cf-black"
        >
          Skip to content
        </a>
        {children}
      </body>
    </html>
  );
}
