import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "CourtFuel — AI nutrition for basketball players",
  description:
    "Scan any meal, get a basketball-tuned score, fuel your game. iOS app in private beta.",
  openGraph: {
    title: "CourtFuel — AI nutrition for basketball players",
    description:
      "Scan any meal, get a basketball-tuned score, fuel your game. iOS app in private beta.",
    type: "website",
  },
  // OG image is generated by src/app/opengraph-image.tsx
  // TODO: replace default Next.js favicon with the real CourtFuel app icon
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-cf-black text-white">
        {children}
      </body>
    </html>
  );
}
